services:
  - type: web
    name: cgi-generator
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cgi-generator-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: PIAPI_API_KEY
        sync: false
      - key: FAL_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: JWT_SECRET
        sync: false

databases:
  - name: cgi-generator-db
    databaseName: cgi_generator
    user: cgi_user